# Generated by Django 4.1.6 on 2023-02-18 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_menu_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu", old_name="description", new_name="menu_item_description",
        ),
    ]
